server:
  port: 9091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security-user-name-and-password
    username: blaise
    password: postgres123
  jpa:
    hibernate:
      ddl-auto: update
