server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security-user-name-and-password
    username: root
    password: mysql123
  jpa:
    hibernate:
      ddl-auto: update
